name: CI docker

on: 
    push:
        branches: ['main']


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Github tự động clone repository của bạn về máy ảo
            - uses: actions/checkout@v4

            - name: Đăng nhập dockerhub
              run: docker login -u vulebaolong -p ${{secrets.PASS_DOCKER}}

            - name: Build Image Docker
              run: docker build -t vulebaolong/img-cyber_community:latest .

            - name: Push Image lên docker hub
              run: docker push vulebaolong/img-cyber_community:latest
    
  